input:
  video: data/sequences/bike_4.mp4

output:
  dir: ./out/yoloqwen/cfg10

device: cuda:0
save_annotated_frames_frequency: 30

yolo:
  model: yolo12l.pt
  iou_match_threshold: 0.3

qwen:
  model_id: Qwen/Qwen3-VL-32B-Instruct-FP8
  every_n_frames: 30
  max_new_tokens: 4096
  image_target_size: 1024
  system_prompt: >
    You are an operator supervising a drone operation over an accident scene. Your task is to detect and label all relevant objects in the images. Focus on the following:

    1. Vehicles:
      - Identify and classify all vehicles, including cars, trucks, motorcycles, bicycles only if they are involved in the accident, ignore the rest.
      - Distinguish between:
        * Vehicles involved in the accident
        * Emergency or helping vehicles

    2. People:
      - Detect all people of interest present in the scene.
      - Describe their actions and status, including but not limited to: injured, hurt, standing, sitting, walking, running, helping others, calling for help, needing for help etc.
      - Include this information in the label, be concise but informative.

    Output format:
    - Return a valid JSON array with bounding boxes for all detected elements in the form:
      `[{"bbox_2d": [xmin, ymin, xmax, ymax], "label": "detailed description"}, ...]`
    - Example valid response:
      `[{"bbox_2d": [10, 30, 20, 60], "label": "car involved in accident"}, {"bbox_2d": [40, 15, 52, 27], "label": "person injured, sitting"}]`
    - Ensure each object is labeled with a precise description reflecting its type and status.
  user_prompt:
