grid: TrainSAM3

parameters:
  model:
    - name: "sam"

  classes: [["crashed_car", "person", "car"]]

  train:
    data: ["data/VistaCrash/data.yaml"]

  val:
    data: ["data/VistaCrash/data.yaml"]
    split: ["test"]

other_grids:

