#!/bin/bash

export HF_HOME=$SCRATCH
export TORCH_HOME=$SCRATCH
export AFFEX_CACHE_DIR=$SCRATCH/affex_cache

echo "HF_HOME: $HF_HOME"
echo "TORCH_HOME: $TORCH_HOME"
echo "AFFEX_CACHE_DIR: $AFFEX_CACHE_DIR"

source .venv/bin/activate

export TMPDIR=./tmp
python main.py run $@
