#!/bin/bash

export HF_HOME=$SCRATCH
export TORCH_HOME=$SCRATCH

echo "HF_HOME: $HF_HOME"
echo "TORCH_HOME: $TORCH_HOME"

source .venv/bin/activate

export TMPDIR=./tmp
python main.py run $@ --function computational
