#!/bin/bash

#SBATCH -A IscrC_DELIGHT
#SBATCH -p boost_usr_prod
#SBATCH --qos normal
#SBATCH --time=24:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=32
#SBATCH --gres=gpu:1
#SBATCH --mem=123000
#SBATCH --job-name=DCAMA
#SBATCH --out=out/dcama.log
#SBATCH --err=out/dcama.log

srun ./scripts/train_res.sh
